### ISSUE TITLE
Not available on NPM/Yarn

### ISSUE THREAD

**Issue by cjke** [goopscoop/svg-to-react-cli#3]
Cool library. Just a heads up - not published to Yarn/NPM:

![image](https://cloud.githubusercontent.com/assets/884065/20379981/78df8d66-ace2-11e6-9e0f-1d46bb1fb785.png)

**Comment by goopscoop** [comment]
Interesting. That's new. I'll take a look and see what happened. Thanks.

**Comment by cjke** [comment]
Thanks. I know the same thing has happened to flowtype - where things did publish correctly and stopped latest releases from appearing in the npm manifest. Let me know if I can run any validation at the other end.

**Comment by goopscoop** [comment]
I see what happened. The package is `svg-to-react-cli`. You attempted `react-to-svg-cli`

**Comment by goopscoop** [comment]
I'll update the docs, that was my bad. Thanks for bringing this up

**Comment by cjke** [comment]
Heh - all good! At least I'm not going crazy.
