### ISSUE TITLE
Safer file management

### ISSUE THREAD

**Issue by cjke** [goopscoop/svg-to-react-cli#4]
Currently the script allows the destruction of existing files without confirmation. This is potentially very risky. 

Please consider some safer file management. Happy to do some PR's if needed

**Comment by goopscoop** [comment]
That's a good point. I can add that feature, but I won't be able to get to it til next week. If you want to submit a PR for it, that'd be great. Otherwise I'll jump on it next week.

**Comment by cjke** [comment]
Cool. I should be freed up around Monday arvo (EST), I will try to get some PR's in order.

**Comment by goopscoop** [comment]
Sounds great! 👍

**Comment by cjke** [comment]
Fixed by PR #6
